// =========================================== 
// PSYCHROMETRIC EXCEL EXPORT
// Export psychrometric calculations to Excel
// with process chains and load calculations
// =========================================== 

import * as XLSX from 'xlsx'
import type {
  PsychrometricSystem,
  PsychrometricPoint,
  PsychrometricProcess,
  StatePointResult,
  ProcessType,
} from '../types/psychrometric'
import { barometricPressureAtAltitude } from '../data/psychrometricConstants'
import { calculateProcess } from '../calculations/psychrometric'

// Process type display names
const PROCESS_NAMES: Record<ProcessType, string> = {
  sensible_heating: 'Sensible Heating',
  sensible_cooling: 'Sensible Cooling',
  evaporative_cooling: 'Evaporative Cooling',
  steam_humidification: 'Steam Humidification',
  dx_dehumidification: 'DX Dehumidification',
  desiccant_dehumidification: 'Desiccant Dehumidification',
  mixing: 'Air Mixing',
  oa_ra_mixing: 'OA/RA Mixing',
  space_load: 'Space Load',
  custom: 'Custom Process',
}

export function exportPsychrometricToExcel(
  system: PsychrometricSystem,
  points: PsychrometricPoint[],
  calculatedPoints: Record<string, StatePointResult>,
  processes?: PsychrometricProcess[]
): void {
  const workbook = XLSX.utils.book_new()
  const pressure = barometricPressureAtAltitude(system.altitudeFt)
  
  // =========================================== 
  // Sheet 1: Summary
  // =========================================== 
  const summaryData: (string | number | null)[][] = [
    ['PSYCHROMETRIC ANALYSIS - SUMMARY'],
    [],
    ['System Information'],
    ['System Name', system.name],
    ['Generated', new Date().toLocaleDateString()],
    ['Generated By', 'HVAC Calculator App'],
    [],
    ['Atmospheric Conditions'],
    ['Altitude', `${system.altitudeFt} ft`],
    ['Barometric Pressure', `${pressure.toFixed(3)} psia`],
    ['Barometric Pressure', `${(pressure * 29.921 / 14.696).toFixed(2)} in.Hg`],
    [],
    ['Unit Settings'],
    ['Temperature Unit', system.tempUnit === 'F' ? 'Fahrenheit' : 'Celsius'],
    ['Humidity Unit', system.humidityUnit === 'grains' ? 'grains/lb' : 'lb/lb'],
    [],
    ['Statistics'],
    ['Total State Points', points.length],
    ['Total Processes', processes?.length || 0],
  ]
  
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData)
  summarySheet['!cols'] = [{ wch: 25 }, { wch: 35 }]
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary')
  
  // =========================================== 
  // Sheet 2: State Points
  // =========================================== 
  const pointsHeader = [
    'Point Label',
    'Type',
    'Dry Bulb (°F)',
    'Wet Bulb (°F)',
    'Dew Point (°F)',
    'RH (%)',
    'Humidity Ratio (gr/lb)',
    'Humidity Ratio (lb/lb)',
    'Enthalpy (Btu/lb)',
    'Sp. Volume (ft³/lb)',
    'Vapor Pressure (psia)',
    'CFM',
  ]
  
  const pointsData: (string | number)[][] = [pointsHeader]
  
  points.forEach(point => {
    const result = calculatedPoints[point.id]
    if (result) {
      pointsData.push([
        point.pointLabel,
        point.pointType,
        result.dryBulbF.toFixed(2),
        result.wetBulbF.toFixed(2),
        result.dewPointF.toFixed(2),
        result.relativeHumidity.toFixed(2),
        result.humidityRatioGrains.toFixed(2),
        result.humidityRatioLb.toFixed(6),
        result.enthalpyBtuLb.toFixed(2),
        result.specificVolumeFt3Lb.toFixed(4),
        result.vaporPressurePsia.toFixed(4),
        point.cfm || 0,
      ])
    }
  })
  
  const pointsSheet = XLSX.utils.aoa_to_sheet(pointsData)
  pointsSheet['!cols'] = [
    { wch: 15 },
    { wch: 10 },
    { wch: 12 },
    { wch: 12 },
    { wch: 12 },
    { wch: 8 },
    { wch: 18 },
    { wch: 18 },
    { wch: 15 },
    { wch: 18 },
    { wch: 15 },
    { wch: 10 },
  ]
  XLSX.utils.book_append_sheet(workbook, pointsSheet, 'State Points')
  
  // =========================================== 
  // Sheet 3: HVAC Processes (from stored processes)
  // =========================================== 
  if (processes && processes.length > 0) {
    const processHeader = [
      '#',
      'Process Name',
      'Label',
      'Description',
      'Type',
      'Start Point',
      'Start DB (°F)',
      'Start WB (°F)',
      'End Point',
      'End DB (°F)',
      'End WB (°F)',
      'CFM',
      'Total Load (Btuh)',
      'Sensible Load (Btuh)',
      'Latent Load (Btuh)',
      'Tons',
      'Moisture (lb/hr)',
      'SHR',
      'Chained',
    ]
    
    const processData: (string | number)[][] = [processHeader]
    
    let totalSensible = 0
    let totalLatent = 0
    let totalLoad = 0
    let totalTons = 0
    let totalMoisture = 0
    
    processes.forEach((process, idx) => {
      const startPoint = process.startPointId ? calculatedPoints[process.startPointId] : null
      const endPoint = process.endPointId ? calculatedPoints[process.endPointId] : null
      const startPt = points.find(p => p.id === process.startPointId)
      const endPt = points.find(p => p.id === process.endPointId)
      
      // Check if chained from previous
      const isChained = idx > 0 && processes[idx - 1].endPointId === process.startPointId
      
      let result = null
      if (startPoint && endPoint && process.cfm > 0) {
        try {
          result = calculateProcess(startPoint, endPoint, process.cfm)
        } catch (e) {
          console.warn('Failed to calculate process:', e)
        }
      }
      
      processData.push([
        idx + 1,
        process.name,
        process.label || '',
        process.description || '',
        PROCESS_NAMES[process.processType] || process.processType,
        startPt?.pointLabel || '—',
        startPoint?.dryBulbF.toFixed(1) || '—',
        startPoint?.wetBulbF.toFixed(1) || '—',
        endPt?.pointLabel || '—',
        endPoint?.dryBulbF.toFixed(1) || '—',
        endPoint?.wetBulbF.toFixed(1) || '—',
        process.cfm,
        result?.totalLoadBtuh.toFixed(0) || '—',
        result?.sensibleLoadBtuh.toFixed(0) || '—',
        result?.latentLoadBtuh.toFixed(0) || '—',
        result?.totalLoadTons.toFixed(2) || '—',
        result?.moistureLbHr.toFixed(2) || '—',
        result ? (result.sensibleHeatRatio * 100).toFixed(0) + '%' : '—',
        isChained ? 'Yes' : 'No',
      ])
      
      if (result) {
        totalSensible += result.sensibleLoadBtuh
        totalLatent += result.latentLoadBtuh
        totalLoad += result.totalLoadBtuh
        totalTons += Math.abs(result.totalLoadTons)
        totalMoisture += result.moistureLbHr
      }
    })
    
    // Add totals row
    processData.push([])
    processData.push([
      '',
      'TOTALS',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      totalLoad.toFixed(0),
      totalSensible.toFixed(0),
      totalLatent.toFixed(0),
      totalTons.toFixed(2),
      totalMoisture.toFixed(2),
      '',
      '',
    ])
    
    const processSheet = XLSX.utils.aoa_to_sheet(processData)
    processSheet['!cols'] = [
      { wch: 4 },
      { wch: 20 },
      { wch: 18 },
      { wch: 12 },
      { wch: 12 },
      { wch: 12 },
      { wch: 12 },
      { wch: 12 },
      { wch: 12 },
      { wch: 8 },
      { wch: 14 },
      { wch: 14 },
      { wch: 14 },
      { wch: 8 },
      { wch: 14 },
      { wch: 8 },
      { wch: 8 },
    ]
    XLSX.utils.book_append_sheet(workbook, processSheet, 'HVAC Processes')
  }
  
  // =========================================== 
  // Sheet 4: Reference
  // =========================================== 
  const referenceData: (string | number)[][] = [
    ['PSYCHROMETRIC REFERENCE'],
    [],
    ['Constants'],
    ['Standard Air Density', '0.075 lb/ft³'],
    ['Standard Pressure', '14.696 psia'],
    ['Grains per Pound', '7000'],
    [],
    ['Formulas Used'],
    ['Humidity Ratio', 'W = 0.622 × Pw / (P - Pw)'],
    ['Enthalpy', 'h = 0.240×Tdb + W×(1061 + 0.444×Tdb) Btu/lb'],
    ['Specific Volume', 'v = 0.370486×(T+459.67)×(1+1.6078×W)/P ft³/lb'],
    [],
    ['Standard Air Heat Transfer'],
    ['Sensible Heat', 'Qs = 1.08 × CFM × ΔT (Btuh)'],
    ['Total Heat', 'Qt = 4.5 × CFM × Δh (Btuh)'],
    ['Latent Heat', 'QL = 0.68 × CFM × ΔW (Btuh, grains)'],
    [],
    ['Process Types'],
    ['Sensible Heating', 'Temperature increase, constant humidity ratio'],
    ['Sensible Cooling', 'Temperature decrease above dew point'],
    ['Evaporative Cooling', 'Adiabatic saturation along constant WB line'],
    ['DX Dehumidification', 'Cooling below dew point with condensation'],
    ['Steam Humidification', 'Moisture addition at nearly constant DB'],
    ['Desiccant Dehumidification', 'Moisture removal along constant enthalpy'],
  ]
  
  const referenceSheet = XLSX.utils.aoa_to_sheet(referenceData)
  referenceSheet['!cols'] = [{ wch: 25 }, { wch: 50 }]
  XLSX.utils.book_append_sheet(workbook, referenceSheet, 'Reference')
  
  // Generate filename and download
  const filename = `psychrometric_${system.name.replace(/[^a-z0-9]/gi, '_')}_${new Date().toISOString().split('T')[0]}.xlsx`
  XLSX.writeFile(workbook, filename)
}
